apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: nodejs-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: nodejs-app

  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
