apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nodejs-app

  namespaceSelector:
    matchNames:
      - nodejs-app

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
